# Generated by Django 2.1.3 on 2018-11-04 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ref_id', models.CharField(default='ABC', max_length=120, unique=True)),
                ('ip_address', models.CharField(default='ABC', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='joins.Join')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='join',
            unique_together={('email', 'ref_id')},
        ),
    ]
